In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('Soyabean/Soyabean 2019.xls', engine='openpyxl')

BadZipFile: File is not a zip file

In [15]:
df

,commodity_name,state,district,market,min_price,max_price,modal_price,date
0,Ajwan,Gujarat,Amreli,Amreli,63.25,79.55,79.55,2019-05-22
1,Ajwan,Gujarat,Banaskanth,Dhanera,80.05,80.05,80.05,2019-05-22
2,Ajwan,Gujarat,Jamnagar,Jamnagar,90.00,155.00,122.50,2019-05-22
3,Ajwan,Gujarat,Mehsana,Kadi,94.50,112.50,107.00,2019-05-22
4,Ajwan,Gujarat,Mehsana,Unjha,21.25,148.50,99.75,2019-05-22
...,...,...,...,...,...,...,...,...
836972,Arhar (Tur/Red Gram)(Whole),Gujarat,Bharuch,Jambusar(Kaavi),5100.00,5500.00,5300.00,06 Oct 2021
836973,Arhar (Tur/Red Gram)(Whole),Gujarat,Rajkot,Jasdan,3500.00,5500.00,5000.00,06 Oct 2021
836974,Arhar (Tur/Red Gram)(Whole),Gujarat,Rajkot,Rajkot,5300.00,6225.00,5650.00,06 Oct 2021
836975,Arhar (Tur/Red Gram)(Whole),Gujarat,Junagarh,Visavadar,4750.00,5750.00,5250.00,06 Oct 2021
836976,Arhar (Tur/Red Gram)(Whole),Kerala,Kasargod,Neeleswaram,10500.00,11500.00,11000.00,06 Oct 2021

In [16]:
df.shape

(836977, 8)

In [18]:
sort_df = df.sort_values(by = 'state')
sort_df

,commodity_name,state,district,market,min_price,max_price,modal_price,date
834337,its,1.50,3000,5000,NaN,NaN,NaN,NaN
53272,Drumstick,Andaman and Nicobar,Nicobar,Car Nicobar,130.0,170.0,150.0,2019-06-12
57837,Brinjal,Andaman and Nicobar,Nicobar,Car Nicobar,100.0,150.0,120.0,2019-06-11
59576,Potato,Andaman and Nicobar,Nicobar,Car Nicobar,40.0,60.0,50.0,2019-06-13
61330,Onion,Andaman and Nicobar,Nicobar,Car Nicobar,60.0,100.0,80.0,2019-06-11
...,...,...,...,...,...,...,...,...
637144,Potato,West Bengal,Burdwan,Asansol,9.0,11.0,10.5,2021-05-07
36183,Brinjal,West Bengal,Jalpaiguri,Dhupguri,16.5,18.5,17.5,2019-05-29
637147,Potato,West Bengal,Birbhum,Bolpur,8.0,11.0,9.2,2021-05-07
364738,Onion,West Bengal,Malda,English Bazar,58.0,62.0,60.0,2019-11-25
98547,Tomato,West Bengal,Burdwan,Kalna,34.0,35.0,35.0,2019-06-21

In [20]:
df = df[df['state'] == 'Madhya Pradesh']
df

,commodity_name,state,district,market,min_price,max_price,modal_price,date
5,Ajwan,Madhya Pradesh,Neemuch,Neemuch,80.0,132.0,95.0,2019-05-22
11,Alasande+Gram,Madhya Pradesh,Panna,Ajaygarh,41.0,46.2,42.0,2019-05-22
52,Amla(Nelli+Kai),Madhya Pradesh,Neemuch,Neemuch,124.0,124.0,124.0,2019-05-22
104,Apple,Madhya Pradesh,Harda,Harda(F&V),30.0,33.0,32.0,2019-05-22
219,Arhar+Dal(Tur+Dal),Madhya Pradesh,Sagar,Jaisinagar,36.0,38.0,37.0,2019-05-22
...,...,...,...,...,...,...,...,...
836883,Arhar (Tur/Red Gram)(Whole),Madhya Pradesh,Alirajpur,Jobat,4400.0,4550.0,4500.0,05 Oct 2021
836884,Arhar (Tur/Red Gram)(Whole),Madhya Pradesh,Narsinghpur,Narsinghpur,5900.0,6200.0,6000.0,05 Oct 2021
836885,Arhar (Tur/Red Gram)(Whole),Madhya Pradesh,Raisen,Obedullaganj,4000.0,5351.0,4896.0,05 Oct 2021
836886,Arhar (Tur/Red Gram)(Whole),Madhya Pradesh,Ratlam,Sailana,4290.0,4699.0,4494.0,05 Oct 2021
836910,Arhar (Tur/Red Gram)(Whole),Madhya Pradesh,Chhindwara,Saunsar,5700.0,5700.0,5700.0,25 Oct 2021

In [21]:
sort_df = df.sort_values(by = 'commodity_name')

In [22]:
sort_df

,commodity_name,state,district,market,min_price,max_price,modal_price,date
5,Ajwan,Madhya Pradesh,Neemuch,Neemuch,80.00,132.00,95.0,2019-05-22
364603,Ajwan,Madhya Pradesh,Neemuch,Neemuch,45.00,120.00,89.0,2019-09-10
370842,Ajwan,Madhya Pradesh,Neemuch,Neemuch,84.01,122.51,110.0,2019-10-21
376964,Ajwan,Madhya Pradesh,Neemuch,Neemuch,86.01,136.00,106.0,2019-09-16
377732,Ajwan,Madhya Pradesh,Neemuch,Neemuch,66.00,131.76,110.0,2019-10-11
...,...,...,...,...,...,...,...,...
403562,White+Peas,Madhya Pradesh,Jabalpur,Jabalpur,15.00,15.00,15.0,2019-09-25
194804,White+Peas,Madhya Pradesh,Raisen,Udaipura,38.00,42.00,40.5,2019-08-03
589907,Yam+(Ratalu),Madhya Pradesh,Dhar,Dhar(F&V),10.00,18.00,16.0,2019-12-28
578352,Yam+(Ratalu),Madhya Pradesh,Dhar,Dhar(F&V),12.00,17.00,15.0,2019-12-21
604831,Yam+(Ratalu),Madhya Pradesh,Dhar,Dhar(F&V),20.00,29.00,24.0,2021-03-31

In [23]:
df.to_csv('madhya_pradesh_data.csv', index=False)

In [26]:
type(df['date'])

pandas.core.series.Series